# Python Crashcourse


#### Marcel Lüthi, Departement Mathematik und Informatik, Universität Basel

### Python

* interpreter, high-level programming language
* supports imperative, object-oriented and functional programming
* can be very readable
* most popular language for data science

# Learning Python 

- [Einführung in die Programmierung (Onlincourse, in German)](https://dmi-programming.dmi.unibas.ch/eidp/)
- [Python Tutorial](https://docs.python.org/3/tutorial/index.html)
- [List of resources for beginners](https://wiki.python.org/moin/BeginnersGuide)

## Basics

### Comments

Inline-comments start with a `#`.

In [ ]:
# This is a comment
a = 3 # a comment at the end of the line

In [ ]:
# a comment extending
# over several lines needs
# a '#' on each line

### Variables

A variable is declared and defined on the same line. It gets its type from the value on the right hand side. 

In [ ]:
a = 3
a/2

Type-checking is done at runtime. 

In [ ]:
a = "now the variable is a string"
a/2

### Indentation

*Indentation is important!*
* Blocks of statements need to have the same indentation

In [ ]:
# right
a = 5
b = 3

In [ ]:
# wrong
a = 5
  b = 3

## Control structures

### if/elif/else

As any other programming language, Python allows for conditional execution of statements using `if/elif/else` clauses. 

In [ ]:
x = 3

if x > 0:
    print("x is positiv")
elif x == 0:
    print("x is Null")
else:
    print("x is negativ")

### Conditional expressions

`If` can also be used as an expression.

In [ ]:
text = "negativ" if x < 0 else "positiv"
print(text)

### Indentation II

Indentation defines statements that belong together. It takes the role that braces take in other languages (such as java)

In [ ]:
x = -1

if x > 0:
    print("in if")
    print("still in if")
    
print("outside if")

### while-loops

While loops work as in any other language. 

In [1]:
x = 0
while x < 5:
    print(x)
    x = x + 1

0
1
2
3
4


### for-loops

For loops are used when the number of elements to iterate over are known in advance

In [ ]:
for x in range(0, 5):
    print(x)

### Range

`range(start, stop[, step])` generates numbers from `start` to `stop` with a step size of `step`

In [ ]:
for x in range(4, 16, 2):
    print(x)

In [ ]:
for x in range(5, -5, -3):
    print(x)

### Logical operator

Using the logical operators `and`, `or`, `not` we can build arbitrarily complex boolean expressions:

In [ ]:
x = 7
y = 3

print((x > 5) and (y < 3) or (not x == 8))

## Lists and tuples

### Lists

*Lists* represent a sequence of elements (objects of any type)



In [ ]:
l = [3, "Doc", "Cat"]

### Tuple

Like a list, but the number of elements is fixed. The tuple itself is immutable (cannot be changed).

In [ ]:
t = ("parrot", 31, "Bob")

### Indexing

Sequences, such as lists, can be indexed using positive or negative numbes. 
Negative numbers count from the last element. 
The first element has index 0, the last has index -1.

In [ ]:
t = (4, 5, 2, 9)
print(t[1])

In [ ]:
print(t[-2])

### Operations on  lists

In [ ]:
l = ["Cat", "Doc", 32]

In [ ]:
# Assignment
l[2] = "parrot"
print("after assignment", l)


In [ ]:
# add elements at the end
l.append("cat")
print("after append: ", l)


In [ ]:
## Determine the length
print(len(l))


### Slicing

More advanced indexing (called slicing) can be used to obtain ranges of elements

In [ ]:
l = ["a", "b", "c", "d", "e", "f"]
print("First three elements: ", l[:3])
print("Last three elemnts: ", l[len(l)-3:])
print("Elements from the middle: ", l[2:4])
print("Every second element: ", l[0:len(l):2])
print("Backwards: ", l[3::-1])

### Tuple unpacking

*Tupel unpacking* "unpacks" Values on the right hand side and assigns these values to the variables on the left hand side. 

In [ ]:
number, name = (3, "Johann Gambolputty")
print(number)
print(name)

### Dictionaries

Used to store values under a (unique) key. 

* The key is often (but not always) a text. 

In [ ]:
engl_german = {"old" : "alt", "young" : "jung", "happy" : "glücklich"} 

### Accessing and manipulating values

#### Indexing
* Same syntax as with lists

In [ ]:
print(engl_german["young"])

#### Adding values 

* New entry is created if key doesn't exist

In [ ]:
engl_german["new"] = "neu"

### List-Comprehensions

* Flexible and succinct way to define lists.
* Mental model: for loop that returns its values into list

In [14]:
[i*i for i in range(0, 10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### List-Comprehensions (further examples)
Several `for` clauses result in the cartesian procuct. 

In [2]:
[(i, j) for i in range(0, 3) for j in range(0, 4)]

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3)]

An `if`-clause filters the values

In [3]:
[i for i in range(0, 10) if i % 2 == 0]

[0, 2, 4, 6, 8]

### Functions

We can define functions as follows (observe the `:` after the signature.
The keyword `return` returns control back to the caller and yields the value specified after the return. 

In [ ]:
def power(base, exponent):
    return base ** exponent   # base "hoch" exponent

power(2,3)

### Numpy

Library for numerical processing. 

* Needs to be imported

In [10]:
import numpy as np

### Numpy arrays

* Used to represent vectors, matrices and tensors
* provides many functions to operate on numerical data:

##### Examples

In [16]:
a = np.zeros((3,))

In [17]:
b = np.random.uniform(0, 1, size = (5,3))


In [18]:
c = np.array([[1,2],[3,4],[5,6]])

### Shapes of arrays

* It's important to keep track of the shapes of arrays

In [ ]:
print("shape a: ", a.shape)
print("shape b: ", b.shape)
print("shape c: ", c.shape)

### Functions on elements

Functions are applied over all the elements, or the indicated axis

In [19]:
print("sum over all elements: ", np.sum(c))
print("sum over columns: ", np.sum(c, axis=0))
print("sum over rows: ", np.sum(c, axis=1))

sum over all elements:  21
sum over columns:  [ 9 12]
sum over rows:  [ 3  7 11]


### Slicing 
Slicing is used to extract rows, columns or other rectangular slices:

In [20]:
c[0, :] # First row

array([1, 2])

In [21]:
c[:,1] # Second columns

array([2, 4, 6])

In [22]:
c[0:2, 0:2] # Subarray

array([[1, 2],
       [3, 4]])

## Getting help

* Python has an extensive help system built in. 

To get a description of a method, type `help` or `?` after the command.

In [24]:
help(np.bitwise_or)

Help on ufunc:

bitwise_or = <ufunc 'bitwise_or'>
    bitwise_or(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Compute the bit-wise OR of two arrays element-wise.

    Computes the bit-wise OR of the underlying binary representation of
    the integers in the input arrays. This ufunc implements the C/Python
    operator ``|``.

    Parameters
    ----------
    x1, x2 : array_like
        Only integer and boolean types are handled.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs